name: test_redux
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  built_redux: ">=6.1.1 <8.0.0"
  flutter_redux: ^0.5.2
  rxdart: ^0.18.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true